CREATE DATABASE cars;
GRANT ALL PRIVILEGES ON DATABASE cars TO dev;

CREATE DATABASE rentals;
GRANT ALL PRIVILEGES ON DATABASE rentals TO dev;

CREATE DATABASE payments;
GRANT ALL PRIVILEGES ON DATABASE payments TO dev;
